# Generated by Django 4.2.4 on 2023-08-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_delete_loginform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
    ]
