# Generated by Django 4.2.4 on 2023-08-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_product_prodapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
