# Generated by Django 4.2.4 on 2023-08-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_userform_alter_product_selling_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
