# Generated by Django 4.2.4 on 2023-08-31 08:25

import Home.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=Home.custom_fields.TenDigitBigIntegerField(),
        ),
    ]
