# Generated by Django 4.2.4 on 2023-08-31 14:13

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=Home.models.get_local_time),
        ),
    ]
