# Generated by Django 4.2.4 on 2023-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_feedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(unique=True, upload_to='product'),
        ),
    ]
