# Generated by Django 4.2.4 on 2023-08-31 17:30

import Home.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_remove_gallery_hash_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(storage=Home.storage.NoRenameStorageForModel(), unique=True, upload_to='product'),
        ),
    ]
