# Generated by Django 4.2.4 on 2023-08-31 18:24

import Home.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=Home.storage.NoRenameStorageForModel(), upload_to='product'),
        ),
    ]
