# Generated by Django 4.2.4 on 2023-08-31 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_hash',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
