# Generated by Django 4.2.4 on 2023-09-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_gallery_image_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagory',
        ),
    ]
