# Generated by Django 4.2.4 on 2023-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_userloginstat_logout_time_userloginstat_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginstat',
            name='session_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
